In [1]:
import numpy as np

## Numpy array

In [2]:
newList = [20, 30, 40]
type(newList)

list

In [3]:
np.array(newList)

array([20, 30, 40])

In [4]:
matrixList = [[10,20,30],[30,40,50],[50,60,70]]
type(matrixList)

list

In [5]:
np.array(matrixList)

array([[10, 20, 30],
       [30, 40, 50],
       [50, 60, 70]])

## arange

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2) ## 2şer arttır

array([0, 2, 4, 6, 8])

## zeros & ones

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## linspace

In [11]:
np.linspace(0,16,10) ## 0dan 16ya 10 sayı yaz

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

## eye

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random

In [13]:
np.random.randn(8)

array([ 0.62308666, -2.33750507, -2.03498369,  0.51089425, -0.08847479,
        0.65298606, -2.04370324,  0.80786895])

In [14]:
np.random.randn(4,4)

array([[-0.31764215, -0.85919219, -1.36557489,  0.29554385],
       [ 1.3179804 ,  0.04937367,  0.08400986, -1.26180742],
       [-0.00646962,  0.4867866 , -1.83168933, -0.17656521],
       [ 1.31524656,  0.45362721,  0.58213922,  1.06546673]])

In [15]:
np.random.randint(99,1000)

720

In [16]:
np.random.randint(1,10,10)

array([4, 2, 1, 6, 1, 4, 4, 9, 4, 5])

## numpy dizi metotları

In [17]:
randomArray = np.random.randint(1,10,10)
type(randomArray)

numpy.ndarray

In [18]:
randomArray

array([8, 3, 1, 2, 3, 4, 7, 7, 8, 3])

In [19]:
arangeArray = np.arange(10)
arangeArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arangeArray.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [21]:
arangeArray.max()

9

In [22]:
randomArray.min()

1

In [23]:
randomArray.argmax() ## max sayı 6. indexte

0

In [24]:
arangeArray.shape

(10,)

## matrix

In [25]:
matrixList = [[10,20,30],[30,40,50],[50,60,70]]

In [27]:
newMatrix = np.array(matrixList)

In [28]:
newMatrix

array([[10, 20, 30],
       [30, 40, 50],
       [50, 60, 70]])

In [30]:
newMatrix[0:,2]

array([30, 50, 70])

## operations

In [32]:
newArray = np.random.randint(1,100,18)
newArray

array([24, 73, 43,  7, 29,  3, 94, 75, 64, 17, 67, 71, 45, 50, 73,  1, 83,
       51])

In [34]:
result = newArray > 32
result

array([False,  True,  True, False, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True])

In [36]:
newArray[(result)]
#newArray[(newArray > 32)]

array([73, 43, 94, 75, 64, 67, 71, 45, 50, 73, 83, 51])

In [37]:
newArray[(result)] + newArray[(newArray > 32)]

array([146,  86, 188, 150, 128, 134, 142,  90, 100, 146, 166, 102])

In [38]:
np.sqrt(newArray[(result)])

array([8.54400375, 6.55743852, 9.69535971, 8.66025404, 8.        ,
       8.18535277, 8.42614977, 6.70820393, 7.07106781, 8.54400375,
       9.11043358, 7.14142843])